version: "2"
services:

  mongodb:
    image: mongo:latest
    container_name: mongo-container
#    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  patientManagementSystem:
    build: patientManagementSystem
    image: patient-management-system
    container_name: patientManagementSystem
    restart: always
#    network_mode: host
    hostname: localhost
    ports:
      - 9192:9192


  